// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";

import {WithdrawalVerifier} from "contracts/verifiers/WithdrawalVerifier.sol";

/**
 * @notice Puts a proof produced by the TypeScript side in front of the Groth16
 *         verifier this project deploys, and checks it is accepted.
 *
 * @dev This is the seam nothing else covers. Poseidon agreeing across
 *      languages, the LeanIMT roots agreeing, and the `context` encoding
 *      agreeing are each necessary; none of them shows that a proof built in a
 *      browser verifies against the contract that will judge it. If any of
 *      those pieces were subtly wrong, this test is where it surfaces — before
 *      a user has waited for a 17 MB proving key to find out.
 *
 *      The fixture was generated by `packages/bridge/src/prove.ts` against the
 *      ceremony's `withdraw.zkey`, for a withdrawal of 10 USDC out of a 25 USDC
 *      deposit sitting in a four-leaf state tree. `scripts/veil-proof.mts`
 *      regenerates it.
 */
contract WithdrawalProofTest is Test {
    WithdrawalVerifier private verifier;

    uint256[2] private pA = [
        0x19811e282405cd40374318c5befc6b9662d61678daa97795f66ec57a89539bdc,
        0x2f23a76cd7ab2ec48170f040d713fd4cc350cc680f10577a12915d20fa1e394e
    ];

    uint256[2][2] private pB = [
        [
            0x287f6fb907480b69508f8e5e3e2bbd24a051576a40afc83de66382bb80728b91,
            0x1f6e6aa2e03d714380115123479bd197af678fee5ece86056a226ba646718d90
        ],
        [
            0x1301058daf5e7ed6a19e126a63e556e99f47f080c3579471247d214d05fa1cf9,
            0x1164997989b51aa52ba7c60a2ee005fec1b287a6ad523d1a70de103abd1e7d65
        ]
    ];

    uint256[2] private pC = [
        0x00e83ee2b9358d3f3337a7eee11fd8116ad675460ddffaffafd7a152f7c27863,
        0x296bfa0c2a915bc046923425fbbb44c04714eeaab5fabc4e69e3e42ebc46c41a
    ];

    /// @dev newCommitmentHash, existingNullifierHash, withdrawnValue, stateRoot, stateTreeDepth, ASPRoot, ASPTreeDepth, context
    uint256[8] private pubSignals = [
        0x2c3d24610b8922101a0c0e3d097d182d2f77a29f9695385b7337027b13ad2f8a,
        0x10cef9715ffee1674092ac0231ae78a9fe70655454988ed04cf95140381c3f43,
        0x0000000000000000000000000000000000000000000000000000000000989680,
        0x2eafc4205814208dcda118983c90b1be04fe4ea05a07481e2ed6e07b6eb99b5d,
        0x0000000000000000000000000000000000000000000000000000000000000002,
        0x103c0e12b77992bf3762b79581ac4db1630bacbd4a9abff07a46de47ba7f785c,
        0x0000000000000000000000000000000000000000000000000000000000000002,
        0x0000000000000000000000000000000000000000000000000000000000003039
    ];

    function setUp() public {
        verifier = new WithdrawalVerifier();
    }

    function test_theContractAcceptsAProofBuiltInTypeScript() public view {
        assertTrue(verifier.verifyProof(pA, pB, pC, pubSignals), "the deployed verifier rejected a valid proof");
    }

    function test_withdrawnValueIsTenUsdc() public view {
        // 0x989680 = 10_000_000, six decimals. Stated so the fixture cannot be
        // quietly replaced with one that proves something else.
        assertEq(pubSignals[2], 10_000_000);
    }

    function test_aProofCannotBeRepointedAtAnotherWithdrawal() public view {
        // `context` binds the recipient, the fee and the pool. Changing it is
        // exactly what a relayer would have to do to redirect the money.
        uint256[8] memory tampered = pubSignals;
        tampered[7] = pubSignals[7] + 1;

        assertFalse(verifier.verifyProof(pA, pB, pC, tampered), "a tampered context still verified");
    }

    function test_aProofCannotBeInflated() public view {
        uint256[8] memory tampered = pubSignals;
        tampered[2] = 25_000_000;

        assertFalse(verifier.verifyProof(pA, pB, pC, tampered), "a tampered amount still verified");
    }

    function test_aProofCannotBeMovedToAnotherStateRoot() public view {
        uint256[8] memory tampered = pubSignals;
        tampered[3] = pubSignals[3] + 1;

        assertFalse(verifier.verifyProof(pA, pB, pC, tampered), "a tampered state root still verified");
    }

    function test_aProofCannotBeReusedUnderAnotherAssociationSet() public view {
        // The one an unfiltered ASP makes least interesting today, and the one
        // that matters most the moment the policy tightens.
        uint256[8] memory tampered = pubSignals;
        tampered[5] = pubSignals[5] + 1;

        assertFalse(verifier.verifyProof(pA, pB, pC, tampered), "a tampered ASP root still verified");
    }
}
