import { describe, expect, it } from "vitest";

import fixture from "./fixtures/withdraw-proof.json" with { type: "json" };
import { deriveNote } from "./note";
import { buildWithdrawInputs, SpendError, toSolidityProof, type SnarkjsProof, type SpendRequest } from "./prove";
import { MAX_TREE_DEPTH, witnessFor } from "./tree";

const SIGNATURE = `0x${"ab".repeat(65)}` as const;

const note = deriveNote(SIGNATURE, 0);
const change = deriveNote(SIGNATURE, 1);

const leaves = [111n, 222n, 333n];
const stateWitness = witnessFor(leaves, 222n);
const aspWitness = witnessFor([9n, 8n], 8n);

const request: SpendRequest = {
  note,
  change,
  label: 0x3333n,
  existingValue: 25_000_000n,
  withdrawnValue: 10_000_000n,
  stateWitness,
  aspWitness,
  context: 12_345n,
};

describe("building the circuit input", () => {
  it("hands the circuit every signal it declares", () => {
    const inputs = buildWithdrawInputs(request);

    expect(inputs.withdrawnValue).toBe(10_000_000n);
    expect(inputs.existingNullifier).toBe(note.nullifier);
    expect(inputs.newSecret).toBe(change.secret);
    expect(inputs.stateSiblings).toHaveLength(MAX_TREE_DEPTH);
    expect(inputs.ASPSiblings).toHaveLength(MAX_TREE_DEPTH);
    expect(inputs.stateTreeDepth).toBe(BigInt(stateWitness.depth));
  });

  it("refuses to spend more than the note holds, in words rather than an assert failure", () => {
    expect(() => buildWithdrawInputs({ ...request, withdrawnValue: 26_000_000n })).toThrow(SpendError);
    expect(() => buildWithdrawInputs({ ...request, withdrawnValue: 26_000_000n })).toThrow(/cannot pay out/);
  });

  it("refuses a withdrawal of nothing", () => {
    expect(() => buildWithdrawInputs({ ...request, withdrawnValue: 0n })).toThrow(SpendError);
  });

  it("refuses to reuse the spent note as its own change", () => {
    expect(() => buildWithdrawInputs({ ...request, change: note })).toThrow(/different note/);
  });

  it("allows spending the whole note, leaving change of zero", () => {
    const whole = buildWithdrawInputs({ ...request, withdrawnValue: request.existingValue });
    expect(whole.withdrawnValue).toBe(request.existingValue);
  });
});

describe("the shape the contract takes", () => {
  /**
   * Generated by `scripts/veil-proof.mts` and verified by the deployed
   * verifier in `contracts/test/WithdrawalProof.t.sol`. The expected calldata
   * below is snarkjs's own `exportSolidityCallData` output for this proof, so
   * this test pins our conversion against theirs.
   */
  const proof = fixture.proof as unknown as SnarkjsProof;
  const signals = fixture.publicSignals as readonly string[];

  it("swaps each pB coordinate pair, which is the mistake that costs a silent false", () => {
    const converted = toSolidityProof(proof, signals);

    expect(converted.pB[0][0]).toBe(BigInt(proof.pi_b[0]![1]!));
    expect(converted.pB[0][1]).toBe(BigInt(proof.pi_b[0]![0]!));
    expect(converted.pB[1][0]).toBe(BigInt(proof.pi_b[1]![1]!));
    expect(converted.pB[1][1]).toBe(BigInt(proof.pi_b[1]![0]!));
  });

  it("matches the calldata the Solidity test verified against", () => {
    const converted = toSolidityProof(proof, signals);

    expect(converted.pA).toEqual([
      0x19811e282405cd40374318c5befc6b9662d61678daa97795f66ec57a89539bdcn,
      0x2f23a76cd7ab2ec48170f040d713fd4cc350cc680f10577a12915d20fa1e394en,
    ]);
    expect(converted.pB[0][0]).toBe(0x287f6fb907480b69508f8e5e3e2bbd24a051576a40afc83de66382bb80728b91n);
    expect(converted.pC[0]).toBe(0x00e83ee2b9358d3f3337a7eee11fd8116ad675460ddffaffafd7a152f7c27863n);
  });

  it("leaves pA and pC in the order snarkjs gave them", () => {
    const converted = toSolidityProof(proof, signals);

    expect(converted.pA[0]).toBe(BigInt(proof.pi_a[0]!));
    expect(converted.pC[1]).toBe(BigInt(proof.pi_c[1]!));
  });

  it("carries the eight public signals through unchanged", () => {
    const converted = toSolidityProof(proof, signals);

    expect(converted.pubSignals).toHaveLength(8);
    expect(converted.pubSignals[2]).toBe(10_000_000n);
  });

  it("refuses a proof with the wrong number of signals rather than truncating it", () => {
    expect(() => toSolidityProof(proof, signals.slice(0, 6))).toThrow(/8 public signals/);
  });
});
