import raw from "./sample-receipts.json";
import type { Receipt } from "@arcveildev/sdk";

/** Generated by `pnpm gen:receipts` — signed with a throwaway key, never edited by hand. */
export type ReceiptSample = {
  id: string;
  label: string;
  note: string;
  receipts: readonly Receipt[];
};

export const RECEIPT_SAMPLES = raw.samples as unknown as readonly ReceiptSample[];
