import raw from "./sample-receipts.json";
import type { ChainState } from "@/lib/receipt/chain";
import type { Receipt } from "@/lib/receipt/types";

/** Generated by `pnpm gen:receipts` — signed with a throwaway key, never edited by hand. */
export type ReceiptSample = {
  id: string;
  label: string;
  note: string;
  receipts: readonly Receipt[];
};

export const SAMPLE_CHAIN_STATE = raw.chainState as unknown as ChainState;
export const RECEIPT_SAMPLES = raw.samples as unknown as readonly ReceiptSample[];
